### ISSUE TITLE
Restart mcm when cpu/memory limit is hit

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#156]
We have seen the behavior recently, where MCM-pod gets hung due to a shortage of CPU/Memory resources. Restarting the pod helps there, as pod would then release certain cached resources. This issue connects to the vertical autoscaling of resources, which would be a generic solution, though we would expect side-track optimization in mcm, where we restart the pod whenever we see a need. 

Not sure about the implementation details, it could be via scripts in readiness-probe.

**Comment by vlerenc** [comment]
Can you please elaborate how `out of memory` results in a hanging MCM. I would assume the process to be either killed or at definitely fail fatally because a memory allocation failed. Or do we silently hide failed memory allocations?

Also, what is the mechanism how running out of CPU resources can result in a hanging MCM? CPU can be compressed (different than memory), so eventually I would expect MCM to continue. Or do we believe we have some form of dead lock somewhere or something related to the number parallel go routines?

I am trying to understand how either situation explains hanging software, because it would be important for me to understand that in more detail in general. Thanks in advance!

**Comment by prashanth26** [comment]
We have tried to separate all the safety controller loops into their respective reconciliation loops (goroutines) a while ago. And I don't remember running into this ever since. Have we seen this issue lately?

**Comment by prashanth26** [comment]
I think this no longer makes sense. And we have made improvements to memory/CPU utilization lately. WDYT @hardikdr ?

**Comment by hardikdr** [comment]
Yes, let's close it unless we see it again.

/close
