### ISSUE TITLE
Cleanup package names in the GRPC driver proposal and implementation

### ISSUE THREAD

**Issue by amshuman-kr** [gardener/machine-controller-manager#167]
The current package names `grpc/infrapb` and `grpc/infraclient` should be changed to a more meaningful names in both the GRPC driver proposal as the example implementation.

#### Options:
1. `grpc/server` and `grpc/client`
But this does not say anything about drivers.
1. `grpc/mcm` and `grpc/driver`
1. `driver/grpc/server` and `driver/grpc/client`
1. `driver/grpc/mcm` and `driver/grpc/driver`

Any other options?

**Comment by ggaurav10** [comment]
so there are 3 directories in `pkg/grpc/`
1. `infraclient/` has the grpc client related code for bootstrapping the actual cloud provider code (not used by MCM)
1. `infrapb/` has the grpc core files (needed by both MCM and cloud provider)
1. `infraserver/` has the grpc server related code to bootstrap the actual MCM server (not used by external client; that's why no mention of this in the proposal doc)

The `infraclient` is not required by MCM; this only needs to be imported and used by the external cloud provider. MCM acts as place holder currently for this.
Refer https://github.com/ggaurav10/aws-driver-grpc/tree/master/pkg for reference.

Suggestions:
1. `pkg/grpc/infraclient` -> `pkg/driver/grpc/client` (actually not used by MCM. Currently placeholder so that cloud provider code can use it)
1. `pkg/grpc/infrapb` -> `pkg/driver/grpc/grpc_svc`
1. `pkg/grpc/infraserver` -> `pkg/driver/grpc/server`

There is already a `pkg/driver/` which currently holds in-tree driver implementations for aws, azure, etc. which will be removed eventually.
