### ISSUE TITLE
Add SSH keypair to GCP Machines

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#192]
# Issue
SSH keypairs are attached to a machine during machine creation for all providers except GCP at the moment.

# Solution
Investigate where all are the Keypair references missing for GCP and propagate it till Gardener. Make necessary changes to APIs, MCM code and Gardener code.

**Comment by prashanth26** [comment]
FYI @DockToFuture

**Comment by ggaurav10** [comment]
This needs to fixed in the Gardener. There doesn't seem to be need of any change in MCM.
Fix:
https://github.com/ggaurav10/gardener/commit/97b9eab9cd8f90206f09919f793f29a63fe572bf

I have taken liberty to add another flag `enable-oslogin`. It manages ssh access using IAM. Can be removed before merge in upstream if not required.
Upon testing this, i found out that the key does get attached to the instance. However, i was still not able to ssh into the instance using the corresponding private key taken from the secret 'ssh-keypair' in the control plane.
Still looking into it.
@rfranzke and others: any idea why?

**Comment by DockToFuture** [comment]
Did you add a firewall rule to allow ssh access after the key got's propagated to the instance?

**Comment by ggaurav10** [comment]
Thanks for pointing this out.
Made the change:
https://github.com/ggaurav10/gardener/commit/4197cb4058b1e5c57109ed54117deda5a76905e3#diff-392862540dd846bb1c40dab26108d874R71

Even after this, i see same issue. When I try to use the private key to ssh, it asks for password.
On further inspection of the gcp instance, I found out that the key format is invalid (as reported in the console):
```
Invalid key. Required format: <protocol> <key-blob> <username@example.com> or <protocol> <key-blob> google-ssh {"userName": "<username@example.com>", "expireOn": " <date> "}
```
The key only had:
```
ssh-rsa <key-blob>
```
Will need to inspect why this is the case.

**Comment by PadmaB** [comment]
Closing in favor of https://github.com/gardener/gardener/issues/727
