### ISSUE TITLE
Manage azure resources with ARM template.

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#229]
## Issue
Right now, we use multiple calls API to make atomic VM operations like create and delete

## Solution
Combine there create/delete NIC, Disk, and the VM in one ARM template.

**Comment by vlerenc** [comment]
I am not sure whether this is a good approach. Yes, it's what MS suggests and we should take a look, but it reminds me too much of Terraform and the problems we have with it in Gardener like error handling, incomplete requests, retry behaviour (in case stuff didn’t get through and we want to "redo"/"retry") or roll-back behaviour (in case we give up and want to "undo" whatever happened so far). If this would be atomic, then great. However, if it's just a bunch of resources that may be processed only partially (and we have no reason to believe otherwise, because pre-validation won't be possible for Azure, I guess), then it seems suboptimal compared to direct usage of a powerful/programmatic API. I guess, that's what this ticket is about in the end, taking a look to reach a decision, whether ARM templates would improve the situation for us or not?

**Comment by prashanth26** [comment]
Sure Vedran. As you suggested first we would evaluate if the proposed solution makes things better for us, and then only implement it.
