### ISSUE TITLE
[BUG] ALTs are not synced properly to nodes

### ISSUE THREAD

**Issue by PadmaB** [gardener/machine-controller-manager#292]
**Issue:** Custom annotations/labels/taints defined on the shoot yaml are sometimes missed on the newly created nodes

**Observations made:** The nodes went up to 3 once, all missing the label some minutes. The label seemed to be present for the first few minutes [at least for one of them], then the label disappeared

**Comment by prashanth26** [comment]
The most likely cause for the above issue seems to be in the [cluster autoscaler](https://github.com/gardener/autoscaler/tree/machine-controller-manager/cluster-autoscaler) which vendors in the old machine APIs that doesn't understand the nodeSpec (containing the annotations/labels/taints). Credits: @hardikdr 

The fix for the same would be to re-vendor the new MachineAPIs by the cluster autoscaler. 

We need to double-check the cause and fix this. Will keep this thread updated about the same.

**Comment by hardikdr** [comment]
I could confirm this later, it is the Cluster Autoscaler overwriting the MachineDeployment. 
We will re-vendor the autoscaler the fetch the latest MCM, and fix this bug.
