### ISSUE TITLE
Nodes with read-only file system

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#312]
## Issue
Nodes found with a read-only file system

## What exactly happened 

Quoting @vlerenc below,

There were many pods like this on a cluster:
```
istio-system         istio-policy-59b7f4ccd5-zvkgh                                     0/2     UnexpectedAdmissionError   0          7h54m
```
In total:
```
$ ka get pods | grep UnexpectedAdmissionError | wc -l
3754
```
Pod status 
```
$ kn istio-system describe pod istio-policy-59b7f4ccd5-zzwjk
....
Message:            Pod Update plugin resources failed due to failed to write checkpoint file "kubelet_internal_checkpoint": open /var/lib/kubelet/device-plugins/.807306059: read-only file system, which is unexpected.
...
```
`read-only file system, which is unexpected`? So did that happen during the night? Why? Unfortunately, without NPD, we have no automatism that would remedy the situation and replace the machines. Still, strange that it happened, and it seemed to have happened with all 3 machines (the cluster has 3) because I couldn't get op on either.

After the machines were replaced, everything looked healthy again. So I am wondering - what happened and why did the file-system go into a read-only mode?

## Need

To investigate why nodes are running into this issue

**Comment by dguendisch** [comment]
This situation arises when the root filesystem gets corrupt (no clue why that happens though). In this case the kernel remounts the filesystem as read-only.
NPD simply watches for this event in the kernel logs (by grepping for a string https://github.com/kubernetes/node-problem-detector/blob/b8ce6360d93d61eacf9f7442d344f8fb263a38af/config/kernel-monitor.json#L62)

I could reproduce such failure situations by corrupting the filesystem on my own (e.g. overwriting the first 10kb of the root partition with garbage `dd if=/dev/urandom of=/dev/sda9 count=10 bs=1024 seek=0` on the host if `sda9` is your root partition).
Be aware however that doing it this way has other side-effects: for whatever reason this corruption  also affects the kubelets `DiskPressure` check and it will report `DiskPressure: True` (although there is no "real" disk pressure and in the "real" corruption cases we found on our cluster, only the filesystem was corrupted without the kubelet `DiskPressure` condition going to `True`, so `dd`-ing is a little bit different than what we observe, still it's good enough to corrupt it. If it's only about testing NPD, you can simply fake the log message instead of really corrupting the filesystem.)

**Comment by vlerenc** [comment]
I am also not confident that we would find the root cause, but we can/should certainly get NPD in and let MCM act on it.

**Comment by prashanth26** [comment]
NPD - https://github.com/gardener/machine-controller-manager/issues/28

**Comment by cunio-martin** [comment]
I was facing the same issue, which occurred on multiple EC2-based nodes at the same time. Since the issue escalated internally (having 10k+ pods in `UnexpectedAdmissionError` status) it dragged down our HA cluster.

**Comment by hardikdr** [comment]
Hi @cunio-martin, this was fixed recently with following PRs on [gardener](https://github.com/gardener/gardener/pull/1525) and [mcm](https://github.com/gardener/machine-controller-manager/pull/348).

Basically gardener now deploys the NPD and, MCM supports a flag [node-conditions](https://github.com/gardener/machine-controller-manager/blob/master/kubernetes/deployment/deployment.yaml#L31) - if any of those node-conditions are set for the `health-timeout` period[~10mins], MCM replaces the machine by new one.  
- Just to mention, ReadOnlyFileSystem is interpreted via following [pattern](https://github.com/kubernetes/node-problem-detector/blob/master/config/kernel-monitor.json#L62) in NPD.
