### ISSUE TITLE
Azure VM deletions fail due to locks

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#368]
## Issue

VM deletion was failing on a shoot that had locks specified on Azure VMs. 

## Solution

We need to identify the reason why these locks exist on only certain subscriptions and how to get rid of them (or) prevent them from happening in future instances.

**Comment by prashanth26** [comment]
Reference link to Azure locks - https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-lock-resources

**Comment by prashanth26** [comment]
Some important points to note from the above blog -

### Who can manage locks?
To create or delete management locks, you must have access to Microsoft.Authorization/* or Microsoft.Authorization/locks/* actions. Of the built-in roles, only Owner and User Access Administrator are granted those actions.

### How are locks applied
When you apply a lock at a parent scope, all resources within that scope inherit the same lock. Even the resources you add later inherit the lock from the parent. The most restrictive lock in the inheritance takes precedence.

### Removing locks from Azure resources

https://xebia.com/blog/remove-locks-from-azure-resources/

**Comment by dkistner** [comment]
Hmm it seems it happened in combination with resource group level locks. This is an issue for Kubernetes in general and not only for Gardener and the MCM. 

MCM would need to remove the delete lock from the resource group before it delete the virtual machine and its corresponding resources, because if the lock is set it will be recursively applied to all resources in the resource group.

Even so the Kubernetes/Cloud Controller Manager and CSI would need to do the same in case that a volume or a public ip (lb service) should be deleted. This is AFAIK not supported by the Kubernetes Azure cloud provider and as long that isn't the case it makes from my point of view no sense to look the resource group which contains the cluster resources.

**Comment by vlerenc** [comment]
As far as we have now understood, locks were set manually by the users and they have broken themselves. We are not accidentally creating them and we shouldn't get rid of them either (someone set them on purpose). If set, they anyways break the dynamic behaviour of K8s, too.
