### ISSUE TITLE
Potential endless loop during Machine creation

### ISSUE THREAD

**Issue by ialidzhikov** [gardener/machine-controller-manager#382]
Currently on machine creation we have the following code fragment:
https://github.com/gardener/machine-controller-manager/blob/1c4c328bc937ec1f0b209eb4e901b77ec6c4a3db/pkg/controller/machine.go#L385-L392

If the machine GET request fails, in a `for {}` loop the operation is being retried. 
Currently I faced an issue where the last 83,000 log entries of machine-controller-manager Pod are:
```
Machine GET failed for "shoot--foo--bar--[...]". Retrying, error: machines.machine.sapcloud.io "shoot--foo--bar--[...]" not found
```

Probably there was an operator intervention to remove forcefully the Machine object but I think machine-controller-manager could improve in this case.
There should be max allowed retries or some other technique to avoid endless loop when the Machine is no longer present.

**Comment by prashanth26** [comment]
Hi @ialidzhikov ,

We are improving such scenarios with the changes in OOT. We trying to get rid of any continuous retry loops and multiple updates in single reconciliations. This was a bug/mistake which is trying to be fixed with these changes. Refer - https://github.com/gardener/machine-controller-manager/commit/de94d27f05ebea4b737eef22b4706cc24e88a17d#diff-d8287fe74b5273163c9f6b6c635ad912L365. Hope with the OOT things must get better.

**Comment by prashanth26** [comment]
cc: @hardikdr even I see this issue occurring quite frequently. We need to fix this before the next MCM release.

**Comment by ialidzhikov** [comment]
Thanks for prioritizing this one!

**Comment by ialidzhikov** [comment]
Does it makes sense to do a patch release about it?
We see frequently failed Shoot deletions because of instances which still exist in the cloud provider.

**Comment by prashanth26** [comment]
Hi @ialidzhikov ,

We are creating a major release by the end of the day today with this fix.  Apologizes for the delay.
