### ISSUE TITLE
Enable end-user to trigger the deletion/replacement of the machine.

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#390]
## Improvement
Currently, the end-user of MCM only gets to see the node-objects. We have seen the cases where the end-user might want to delete or replace the specific buggy-machine in the cluster. We should probably provide a mechanism to end-user of triggering the replacement of the machine. 
- One of the seemingly natural ways could be via labels/annotations on the node-object.

**Comment by vlerenc** [comment]
Today they would delete the VM in their IaaS console, wouldn't they? In that case, MCM would notice, remove the machine resource and add a new one and by that also a new node, right? Tat is not sufficient/considered too cumbersome/inconvenient?

**Comment by hardikdr** [comment]
Yes, today users could simply delete the VM from infrastructure, and MCM would replace the machine after the `health-timeout` period occurs. This could be slightly inconvenient, mainly for the following reasons.
- In case the `health-timeout` is set comparatively larger, the user might have to wait that much time for replacing even a buggy machine. 
- Few of the end-users might not have access to the infra-console to trigger the deletion.

**Comment by amshuman-kr** [comment]
How about just deleting the 'Node'? There are no access issues there. Are there timeouts involved there too?

**Comment by hardikdr** [comment]
The `health-timeout` period would be entertained even in case of missing/deleted node-object. But the solution could be in this direction, as it does not need the infra-access.

**Comment by vlerenc** [comment]
While we are at it, let's also consider (in this or another ticket) cases where the VM is gone and the IaaS would return a 404.

I.e., does it make sense to bypass the `health-timeout` if:
1. Node gets annotated (clean way to properly terminate a VM/node)
2. Node gets deleted (brute-force way, which has negative consequences on the workload, which is why we don't want to make it our default proposal and we therefore officially say (1))
3. VM is clearly gone/no longer in the IaaS (IaaS returns a clear 404 that can't be misinterpreted as anything but that the VM is truly gone).

Does that make sense? In any case, it would feel more natural, knowing that MCM actually knows about both sides, actually all three sides: MCM machines, K8s nodes, IaaS VMs.

**Comment by Gerrit91** [comment]
With metal-stack we have end-users working quite a lot with local volumes and due to this reason our `health-timeout` is configured high. We do this as a safety measure to prevent user data from getting deleted in case something goes terribly wrong in the landscape for a longer period of time.

As long as we do not offer a wider spectrum of cloud storage for our cloud solution, we would also be very interested in this feature.
