### ISSUE TITLE
Wait until volume is attached on another node

### ISSUE THREAD

**Issue by prashanth26** [gardener/machine-controller-manager#561]
**What happened**:
While draining machines currently MCM waits for Pod PV detachments serially one by one. However, it doesn't wait for the PV to be re-attached on another node. 

**What you expected to happen**:
- To not continue with the next pod-with-volume before the previous one is not only detached but also (re)attached to whatever node.
- Configure Azure clusters with a longer grace period of 5m (instead of 2.5m)

**How to reproduce it (as minimally and precisely as possible)**:
Create a machine with PVs attached and perform a rolling update on the cluster and watch on PVs. 

**Anything else we need to know**:
This creates serious downtimes on Azure with several disks attached to a single VM. 
Changes to be made [here](https://github.com/gardener/machine-controller-manager/blob/master/pkg/controller/drain.go#L669-L680)

**Environment**:
/platform azure
/area quality
/effort 1w

**Comment by vlerenc** [comment]
It would be great to get this implemented. Could someone outside the out-of-tree work do that @prashanth26 ?

Basically, the idea is to not only wait for detach and “hope for the best”, i.e. that we have sufficiently “slowed down” the progress, so that slow infrastructures can cope, but to also track whether the volume got attached again. There are problems with that, though:
- There is no guarantee, the pod will meet the condition and be scheduled at all. Then the process would wait until the timeout lapses before commencing.
- The actual problem is the attach to the new node, but you don’t know in advance where a drained pod will be scheduled to and which contention you are creating, i.e. the attach operation may be slow, because another node is already attaching another volume from a pod that was drained from another node.

The former may not be a real problem. The latter can be controlled by `maxSurge`, i.e. if there is only one node being drained at a time (e.g. for an ETCD worker pool), then only this node can yield pods that need to be scheduled, one by one, hence only the currently drained pod will need a volume to be attached somewhere else, but because no other pod from another node is being drained at the same time, that node will not be busy attaching another volume if MCM waits for each and every pod until it gets its volume attached (with a few exceptions like vertical scaling, that may result in additional detach/attach operations, but this can be ignored).

**Comment by vpnachev** [comment]
With the CSI migration, there is a resource named [VolumeAttachment](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#volumeattachment-v1-storage-k8s-io) that holds some information about the attachment state of a volume to a node. But this should be additionally researched whether it is reliable information for the MCM to decide if all volumes are attached successfully before to proceed with the next machine. Note, these resources seems to be not available in clusters that are still using the in-tree volume provider.

**Comment by prashanth26** [comment]
> It would be great to get this implemented. Could someone outside the out-of-tree work do that @prashanth26 ?
> 
> Basically, the idea is to not only wait for detach and “hope for the best”, i.e. that we have sufficiently “slowed down” the progress, so that slow infrastructures can cope, but to also track whether the volume got attached again. There are problems with that, though:
> 
> * There is no guarantee, the pod will meet the condition and be scheduled at all. Then the process would wait until the timeout lapses before commencing.
> * The actual problem is the attach to the new node, but you don’t know in advance where a drained pod will be scheduled to and which contention you are creating, i.e. the attach operation may be slow, because another node is already attaching another volume from a pod that was drained from another node.
> 
> The former may not be a real problem. The latter can be controlled by `maxSurge`, i.e. if there is only one node being drained at a time (e.g. for an ETCD worker pool), then only this node can yield pods that need to be scheduled, one by one, hence only the currently drained pod will need a volume to be attached somewhere else, but because no other pod from another node is being drained at the same time, that node will not be busy attaching another volume if MCM waits for each and every pod until it gets its volume attached (with a few exceptions like vertical scaling, that may result in additional detach/attach operations, but this can be ignored).

Yes @vlerenc. I think one of us should pick this up. I will discuss this with the team and try to prioritize this (hence changing the milestone back to Q1).

> With the CSI migration, there is a resource named [VolumeAttachment](https://v1-18.docs.kubernetes.io/docs/reference/generated/kubernetes-api/v1.18/#volumeattachment-v1-storage-k8s-io) that holds some information about the attachment state of a volume to a node. But this should be additionally researched whether it is reliable information for the MCM to decide if all volumes are attached successfully before proceeding with the next machine. Note, these resources seem to be not available in clusters that are still using the in-tree volume provider.

I remember in the past @amshuman-kr had observed some inconsistencies with the volume attachments (flapping of state) on the node objects. However, this is something that can be explored while making this change.

**Comment by prashanth26** [comment]
Some points on the discussions made offline.

From the initial looks of it, looks like `VolumeAttachments` isn't available for all clusters. Is probably CSIDriver specific and k8s version (?), we will have to handle the other cases without CSI drivers differently (could be as simple as waiting for a constant additional timeout).

I will try to dig deeper about `VolumeAttachments` resources mentioned by @vpnachev above. Will sync up with him if i need more insights into it. Also, we can think of standardizing/enforcing this feature for important clusters, because without this feature we will have to keep a watch on all node volumes in the cluster while waiting for reattachment which would be expensive.

 @amshuman-kr - has also suggested an alternative approach of tracking the scalesubresource owner reference from pods where can use subresource to track if replica is back up. This has some pros and cons as a well.  

Solution is still under investigation.

**Comment by prashanth26** [comment]
This issue should address some points here - https://github.com/gardener/machine-controller-manager/issues/470#issuecomment-642583382.

**Comment by prashanth26** [comment]
Related - https://github.com/gardener/machine-controller-manager/issues/468.

**Comment by prashanth26** [comment]
/unassign
Paused in favour of other activites

**Comment by prashanth26** [comment]
- [x] Changes on Volume attachments 
- [x] Changes required for timeout 
- [ ] Fixing the mock tests to return correct values for listeres
- [ ] Add unit tests

**Comment by prashanth26** [comment]
Fixed with https://github.com/gardener/machine-controller-manager/pull/608. 
/close
