### ISSUE TITLE
Safety Controller may falsely assume VM orphans and throws machines away

### ISSUE THREAD

**Issue by Gerrit91** [gardener/machine-controller-manager#657]
**How to categorize this issue?**

/area robustness
/kind bug
/priority 3

**What happened**:

There seems to be a chance of the MCM throwing away all worker nodes of a cluster due to orphan deletion. In our case, this happened directly after restart of the machine-controller-manager while the seed cluster's kube-apiserver was unavailable. The MCM then assumed existing machines as orphans and deleted them immediately:

```
I1109 14:56:54.687183       1 machine_safety.go:53] reconcileClusterMachineSafetyOrphanVMs: Start
I1109 14:56:56.009135       1 core.go:174] deleted machine "shoot--phjjbm--s3-test-01-group-0-77fc5-sr5zn" ("00000000-0000-0000-0000-ac1f6b7d7efa")
I1109 14:56:56.009192       1 machine_safety.go:297] SafetyController: Orphan VM found and terminated VM: shoot--phjjbm--s3-test-01-group-0-77fc5-sr5zn, metal:////00000000-0000-0000-0000-ac1f6b7d7efa
I1109 14:56:56.425097       1 core.go:174] deleted machine "shoot--phjjbm--s3-test-01-group-0-77fc5-qldng" ("00000000-0000-0000-0000-ac1f6b7d7e32")
I1109 14:56:56.425158       1 machine_safety.go:297] SafetyController: Orphan VM found and terminated VM: shoot--phjjbm--s3-test-01-group-0-77fc5-qldng, metal:////00000000-0000-0000-0000-ac1f6b7d7e32
I1109 14:56:56.842225       1 core.go:174] deleted machine "shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6" ("00000000-0000-0000-0000-ac1f6b7d7dc6")
I1109 14:56:56.842274       1 machine_safety.go:297] SafetyController: Orphan VM found and terminated VM: shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6, metal:////00000000-0000-0000-0000-ac1f6b7d7dc6
I1109 14:56:56.842441       1 machine_safety.go:68] reconcileClusterMachineSafetyOrphanVMs: End, reSync-Period: 30m0s
I1109 14:59:01.374674       1 machine_util.go:554] Conditions of Machine "shoot--phjjbm--s3-test-01-group-0-77fc5-qldng" with providerID "metal:///fra-equ01/00000000-0000-0000-0000-ac1f6b7d7e32" and backing node "shoot--phjjbm--s3-test-01-group-0-77fc5-qldng" are changing
W1109 14:59:01.374717       1 machine_util.go:562] Machine shoot--phjjbm--s3-test-01-group-0-77fc5-qldng is unhealthy - changing MachineState to Unknown
```

Te MCM leaves behind three machine objects:

```
❯ k get machine
NAME                                            STATUS    AGE
shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6   Unknown   217d
shoot--phjjbm--s3-test-01-group-0-77fc5-qldng   Unknown   217d
shoot--phjjbm--s3-test-01-group-0-77fc5-sr5zn   Unknown   217d
```

**What you expected to happen**:

Worker nodes are not thrown away.

**How to reproduce it (as minimally and precisely as possible)**:

Was not yet able to reproduce it, I will still try and add to the comments if I am able to make it.

**Anything else we need to know?**:

From the code, I think the only possibility that this can happen is because the client maintains a cache and the cache was empty immediately after restart of the pod. In case the cache was empty, a "not found" error would be returned, which to me looks like the only possibility to reach the orphan cleanup part in the code.

I would like to ask three additional questions about the machine safety controller implementation:

1. Why is the cache wait only executed when a cluster has more than one machine? Why does it not apply for single machine clusters? (https://github.com/gardener/machine-controller-manager/blob/v0.41.0/pkg/util/provider/machinecontroller/machine_safety.go#L254)
1. For which reason was the modification of the cache on the `WaitForCacheSync` function introduced? (https://github.com/gardener/machine-controller-manager/blob/6731383c3133ba339b624093c335591ebf6df637/pkg/util/provider/cache/cache.go#L38)
1. Would it make sense to check that `machine.Spec.ProviderID` is not an empty string (https://github.com/gardener/machine-controller-manager/blob/v0.41.0/pkg/util/provider/machinecontroller/machine_safety.go#L270) or let the controller check multiple times before taking any action immediately?

**Environment**:

- Kubernetes version v1.18.20 (seed cluster)
- Cloud provider or hardware configuration: metal-stack
- Others:

**Comment by AxiomSamarth** [comment]
Hey Gerrit,

Whenever the API server of the control cluster or the target cluster is down/unreachable MCM freezes Machine Controller and also freezes the machineDeployment object so that there are no new machines created. However, the machine deployments will still be processed for scale down events. I will try to reproduce, the scenario where the APIServers of the control cluster is down and also MCM is restarted and post my findings here.

Here are the responses to your other questions

> Why is the cache wait only executed when a cluster has more than one machine? Why does it not apply for single machine clusters? (https://github.com/gardener/machine-controller-manager/blob/v0.41.0/pkg/util/provider/machinecontroller/machine_safety.go#L254)

This is to ensure that caching is done only if there is one machine actively running (to avoid caching when the first machine creation is under process)

> For which reason was the modification of the cache on the WaitForCacheSync function introduced? (

This was introduced as the part of K8s client upgrade to v1.20. See [here](https://github.com/gardener/machine-controller-manager/commit/8afbfea8d1b93fbc006ab88f589127b6ad876416)

>Would it make sense to check that machine.Spec.ProviderID is not an empty string 

We will get back on this.

**Comment by AxiomSamarth** [comment]
@Gerrit91 Also, would it be possible for you. to share with us the log dump of MCM from the day this happened?

**Comment by Gerrit91** [comment]
Hey @AxiomSamarth,

till now I was unable to reproduce the issue even though I tried to reconstruct the events that happened on that day. :( 

Here is the full log: [mcm.log](https://github.com/gardener/machine-controller-manager/files/7526833/mcm.log)

**Comment by AxiomSamarth** [comment]
@Gerrit91 I see! One of my colleagues @himanshu-kun is also trying to reproduce this issue. Let's look forward for his findings. 

Thanks for the logs though. I will go through it and check if I find something interesting.

**Comment by himanshu-kun** [comment]
Hi @Gerrit91 , 
The MCM couldn't restart until the API-server is down . By default both MCM contianers tries to acquire leader-lease , and that couldn't be possible if the apiserver is down. 
From from the logs, we see MCM was first struggling to get leader lease and then when API server was up , it acquired it.
```
1109 14:56:00.287125       1 leaderelection.go:325] error retrieving resource lock shoot--phjjbm--s3-test-01/machine-controller: an error on the server ("") has prevented the request from succeeding (get endpoints machine-controller)
E1109 14:56:14.158823       1 leaderelection.go:325] error retrieving resource lock shoot--phjjbm--s3-test-01/machine-controller: an error on the server ("") has prevented the request from succeeding (get endpoints machine-controller)
E1109 14:56:26.535740       1 leaderelection.go:325] error retrieving resource lock shoot--phjjbm--s3-test-01/machine-controller: an error on the server ("") has prevented the request from succeeding (get endpoints machine-controller)
E1109 14:56:39.136200       1 leaderelection.go:325] error retrieving resource lock shoot--phjjbm--s3-test-01/machine-controller: an error on the server ("") has prevented the request from succeeding (get endpoints machine-controller)
I1109 14:56:50.602806       1 leaderelection.go:253] successfully acquired lease shoot--phjjbm--s3-test-01/machine-controller
I1109 14:56:50.603018       1 event.go:282] Event(v1.ObjectReference{Kind:"Endpoints", Namespace:"shoot--phjjbm--s3-test-01", Name:"machine-controller", UID:"48bf7418-d832-40c8-ab77-ae51f6a7c031", APIVersion:"v1", ResourceVersion:"390754371", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' machine-controller-manager-55d44674b6-t9zwk became leader

```

Coming to the problem, after looking at the complete logs , I figured that the cache has been up-to-date , its just that the machine object was referring to some other bare-metal so the ones without machine object were deleted.
If we see this log , which takes values to print from the machine object in cache
```
I1109 14:59:08.159361       1 machine_util.go:554] Conditions of Machine "shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6" with providerID "metal:///fra-equ01/00000000-0000-0000-0000-ac1f6b7d7dc6" and backing node "shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6" are changing
```
we see that machine object's backing bare-metal is `metal:///fra-equ01/00000000-0000-0000-0000-ac1f6b7d7dc6` while if we see the log where safety controller deletes a bare-metal (the machine obj name is taken from the tags on bare-metal in these logs, not the machine obj)
```
I1109 14:56:56.842274       1 machine_safety.go:297] SafetyController: Orphan VM found and terminated VM: shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6, metal:////00000000-0000-0000-0000-ac1f6b7d7dc6
```

we see that the bare-metal `metal:////00000000-0000-0000-0000-ac1f6b7d7dc6` has been referring to machine obj `shoot--phjjbm--s3-test-01-group-0-77fc5-k5wp6` but not vice-versa , hence its orphan and so deleted.

This situation arose because of improper encoding of providerID I guess.
`metal:///fra-equ01/00000000-0000-0000-0000-ac1f6b7d7dc6` != `metal:////00000000-0000-0000-0000-ac1f6b7d7dc6` but the bare-metal machine-ID is same.

After looking at provider-metal [codebase](https://github.com/metal-stack/machine-controller-manager-provider-metal/blob/9fba7df39c3a9d56b63680763f290b52e4da280f/pkg/provider/core.go#L304-L306) , I think the condition here misses the case when  `*m.Partition.ID==""` and because of that the providerID become different even for the same bare-metal machine. Not sure why partition ID could be empty.

Yes I think this confusion would have been avoided with better logging on MCM side also, mentioning the reason of orphan collection, we will improve on that.

**Comment by AxiomSamarth** [comment]
@Gerrit91 If the above investigation has helped you understand the issue and if you are convinced with it then shall we close this issue?

**Comment by Gerrit91** [comment]
I think the answer from @himanshu-kun is great and points us into the right direction. I am pretty much convinced now that there is an inconsistency / a bug somewhere in our code where we construct / manage provider IDs. I did not have the time yet to dig into it though.

I am fine closing this issue and in case there is a reason to further discuss this issue, I would reopen if necessary.

Thanks for your fast help and support. :)
