### ISSUE TITLE
Introduce `make` targets for setup/restore local-manual-setup in mcm-providers

### ISSUE THREAD

**Issue by himanshu-kun** [gardener/machine-controller-manager#865]
**How to categorize this issue?**

/area usability
/kind enhancement
/priority 2

**What would you like to be added**:

https://github.com/gardener/machine-controller-manager/issues/846 introduced `make` targets in MCM Makefile to ease setting up dynamic variables for local testing of MCM and MCM-providers. But such make targets should be added in mcm-provider Makefile also as their development could be done standalone, and thus should not depend on MCM make targets. The `README.md`(for example [provider-aws](https://github.com/gardener/machine-controller-manager-provider-aws/blob/master/README.md#machine-controller-manager-provider-aws)) files under mcm-providers should be updated as well
 
- [ ] aws
- [ ] alicloud
- [ ] gcp
- [ ] azure (include the changes in https://github.com/gardener/machine-controller-manager-provider-azure/pull/124)
- [ ] openstack

**Why is this needed**:
Ease of development

**Comment by sssash18** [comment]
Fixed by: 

- https://github.com/gardener/machine-controller-manager-provider-aws/pull/158
- https://github.com/gardener/machine-controller-manager-provider-azure/pull/141
- https://github.com/gardener/machine-controller-manager-provider-gcp/pull/113
- https://github.com/gardener/machine-controller-manager-provider-alicloud/pull/77
- https://github.com/gardener/machine-controller-manager-provider-openstack/pull/127
