### ISSUE TITLE
Machine should not be recreated incase of MemoryPressure from node object

### ISSUE THREAD

**Issue by hardikdr** [gardener/machine-controller-manager#95]
Currently, MCM recreates the machine if any of the node-condition stays true for the configurable amount of time. MCM basically sees that machine to be Unhealthy and tries to get rid of it. 

Ideally, MCM should recreate the Machine only if DiskPressure is happening. In rest of the cases the scaling of the Machines should be deligated to the cluster-autoscaler or remedy-controller[in-future].

**Comment by prashanth26** [comment]
After discussion the following is the plan decided on.

- Kubelet has to be configured with the right set of parameters to take care of memory/disk pressure in order to evict pods to get rid of disk/memory pressure. Refer - https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#node-conditions.
- Also the mcm's machine health status would be modified to only watch over Kubelet and disk pressure (open to changes until tomorrow morning).
- The machine health failed status computation should be generic enough to adopt to any new conditions being created.

**Comment by amshuman-kr** [comment]
[#98](https://github.com/gardener/machine-controller-manager/pull/98) only covers the condition handling in mcm.

It does not address the kubelet configuration part. Should we create a separate issue for that or keep this ticket open?

**Comment by prashanth26** [comment]
I would prefer keeping this ticket open until it's resolved.

**Comment by prashanth26** [comment]
Reopening issue to address configuration of Kubelet to handle memory/disk pressure handlers.

**Comment by prashanth26** [comment]
Need to address this issue with the help of performance colleagues.

**Comment by amshuman-kr** [comment]
As mentioned [here](https://kubernetes.io/docs/tasks/administer-cluster/out-of-resource/#kubelet-may-not-observe-memory-pressure-right-away), `kubelet` tries to address memory pressure by polling `cAdvisor`. This can miss memory pressure handling if the pressure is acute rather than gradual.

Advice from the above link...
> If you are not trying to achieve extreme utilization, but a sensible measure of overcommit, a viable workaround for this issue is to set eviction thresholds at approximately 75% capacity.

The above approach may not work well for smaller machines.

The alternative is to try out the alpha feature `--experimental-kernel-memcg-notification` in `kubelet` (available since 1.12) which tries to address memory pressure in an event-based way.

**Comment by PadmaB** [comment]
The required changes are made in MCM, however, kubelet configuration is pending.
Closing in favor of [#892](https://github.com/gardener/gardener/issues/892).
